// Generated by gencpp from file voice_keyword_extractor/ExtractKeyword.msg
// DO NOT EDIT!


#ifndef VOICE_KEYWORD_EXTRACTOR_MESSAGE_EXTRACTKEYWORD_H
#define VOICE_KEYWORD_EXTRACTOR_MESSAGE_EXTRACTKEYWORD_H

#include <ros/service_traits.h>


#include <voice_keyword_extractor/ExtractKeywordRequest.h>
#include <voice_keyword_extractor/ExtractKeywordResponse.h>


namespace voice_keyword_extractor
{

struct ExtractKeyword
{

typedef ExtractKeywordRequest Request;
typedef ExtractKeywordResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExtractKeyword
} // namespace voice_keyword_extractor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::voice_keyword_extractor::ExtractKeyword > {
  static const char* value()
  {
    return "e6ee6cf4f2ad6072c8d07a6cc7a7b46a";
  }

  static const char* value(const ::voice_keyword_extractor::ExtractKeyword&) { return value(); }
};

template<>
struct DataType< ::voice_keyword_extractor::ExtractKeyword > {
  static const char* value()
  {
    return "voice_keyword_extractor/ExtractKeyword";
  }

  static const char* value(const ::voice_keyword_extractor::ExtractKeyword&) { return value(); }
};


// service_traits::MD5Sum< ::voice_keyword_extractor::ExtractKeywordRequest> should match
// service_traits::MD5Sum< ::voice_keyword_extractor::ExtractKeyword >
template<>
struct MD5Sum< ::voice_keyword_extractor::ExtractKeywordRequest>
{
  static const char* value()
  {
    return MD5Sum< ::voice_keyword_extractor::ExtractKeyword >::value();
  }
  static const char* value(const ::voice_keyword_extractor::ExtractKeywordRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::voice_keyword_extractor::ExtractKeywordRequest> should match
// service_traits::DataType< ::voice_keyword_extractor::ExtractKeyword >
template<>
struct DataType< ::voice_keyword_extractor::ExtractKeywordRequest>
{
  static const char* value()
  {
    return DataType< ::voice_keyword_extractor::ExtractKeyword >::value();
  }
  static const char* value(const ::voice_keyword_extractor::ExtractKeywordRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::voice_keyword_extractor::ExtractKeywordResponse> should match
// service_traits::MD5Sum< ::voice_keyword_extractor::ExtractKeyword >
template<>
struct MD5Sum< ::voice_keyword_extractor::ExtractKeywordResponse>
{
  static const char* value()
  {
    return MD5Sum< ::voice_keyword_extractor::ExtractKeyword >::value();
  }
  static const char* value(const ::voice_keyword_extractor::ExtractKeywordResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::voice_keyword_extractor::ExtractKeywordResponse> should match
// service_traits::DataType< ::voice_keyword_extractor::ExtractKeyword >
template<>
struct DataType< ::voice_keyword_extractor::ExtractKeywordResponse>
{
  static const char* value()
  {
    return DataType< ::voice_keyword_extractor::ExtractKeyword >::value();
  }
  static const char* value(const ::voice_keyword_extractor::ExtractKeywordResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VOICE_KEYWORD_EXTRACTOR_MESSAGE_EXTRACTKEYWORD_H
