// Generated by gencpp from file voice_keyword_extractor/ExtractKeywordRequest.msg
// DO NOT EDIT!


#ifndef VOICE_KEYWORD_EXTRACTOR_MESSAGE_EXTRACTKEYWORDREQUEST_H
#define VOICE_KEYWORD_EXTRACTOR_MESSAGE_EXTRACTKEYWORDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace voice_keyword_extractor
{
template <class ContainerAllocator>
struct ExtractKeywordRequest_
{
  typedef ExtractKeywordRequest_<ContainerAllocator> Type;

  ExtractKeywordRequest_()
    : start_recording(false)
    , record_seconds(0.0)  {
    }
  ExtractKeywordRequest_(const ContainerAllocator& _alloc)
    : start_recording(false)
    , record_seconds(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _start_recording_type;
  _start_recording_type start_recording;

   typedef float _record_seconds_type;
  _record_seconds_type record_seconds;





  typedef boost::shared_ptr< ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ExtractKeywordRequest_

typedef ::voice_keyword_extractor::ExtractKeywordRequest_<std::allocator<void> > ExtractKeywordRequest;

typedef boost::shared_ptr< ::voice_keyword_extractor::ExtractKeywordRequest > ExtractKeywordRequestPtr;
typedef boost::shared_ptr< ::voice_keyword_extractor::ExtractKeywordRequest const> ExtractKeywordRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator1> & lhs, const ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start_recording == rhs.start_recording &&
    lhs.record_seconds == rhs.record_seconds;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator1> & lhs, const ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace voice_keyword_extractor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ddabba50df5d9f6300be64daba5e3cb6";
  }

  static const char* value(const ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xddabba50df5d9f63ULL;
  static const uint64_t static_value2 = 0x00be64daba5e3cb6ULL;
};

template<class ContainerAllocator>
struct DataType< ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "voice_keyword_extractor/ExtractKeywordRequest";
  }

  static const char* value(const ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool start_recording\n"
"float32 record_seconds\n"
;
  }

  static const char* value(const ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_recording);
      stream.next(m.record_seconds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExtractKeywordRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::voice_keyword_extractor::ExtractKeywordRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "start_recording: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start_recording);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "record_seconds: ";
    Printer<float>::stream(s, indent + "  ", v.record_seconds);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOICE_KEYWORD_EXTRACTOR_MESSAGE_EXTRACTKEYWORDREQUEST_H
