// Generated by gencpp from file voice_keyword_extractor/ExtractKeywordResponse.msg
// DO NOT EDIT!


#ifndef VOICE_KEYWORD_EXTRACTOR_MESSAGE_EXTRACTKEYWORDRESPONSE_H
#define VOICE_KEYWORD_EXTRACTOR_MESSAGE_EXTRACTKEYWORDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace voice_keyword_extractor
{
template <class ContainerAllocator>
struct ExtractKeywordResponse_
{
  typedef ExtractKeywordResponse_<ContainerAllocator> Type;

  ExtractKeywordResponse_()
    : success(false)
    , keyword()
    , transcript()
    , raw_result()
    , error_message()
    , processing_time(0.0)  {
    }
  ExtractKeywordResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , keyword(_alloc)
    , transcript(_alloc)
    , raw_result(_alloc)
    , error_message(_alloc)
    , processing_time(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _keyword_type;
  _keyword_type keyword;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _transcript_type;
  _transcript_type transcript;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _raw_result_type;
  _raw_result_type raw_result;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _error_message_type;
  _error_message_type error_message;

   typedef float _processing_time_type;
  _processing_time_type processing_time;





  typedef boost::shared_ptr< ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ExtractKeywordResponse_

typedef ::voice_keyword_extractor::ExtractKeywordResponse_<std::allocator<void> > ExtractKeywordResponse;

typedef boost::shared_ptr< ::voice_keyword_extractor::ExtractKeywordResponse > ExtractKeywordResponsePtr;
typedef boost::shared_ptr< ::voice_keyword_extractor::ExtractKeywordResponse const> ExtractKeywordResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator1> & lhs, const ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.keyword == rhs.keyword &&
    lhs.transcript == rhs.transcript &&
    lhs.raw_result == rhs.raw_result &&
    lhs.error_message == rhs.error_message &&
    lhs.processing_time == rhs.processing_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator1> & lhs, const ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace voice_keyword_extractor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "915e1fc7f313a415f88e5f75730c00e5";
  }

  static const char* value(const ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x915e1fc7f313a415ULL;
  static const uint64_t static_value2 = 0xf88e5f75730c00e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "voice_keyword_extractor/ExtractKeywordResponse";
  }

  static const char* value(const ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string keyword\n"
"string transcript\n"
"string raw_result\n"
"string error_message\n"
"float32 processing_time\n"
"\n"
;
  }

  static const char* value(const ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.keyword);
      stream.next(m.transcript);
      stream.next(m.raw_result);
      stream.next(m.error_message);
      stream.next(m.processing_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExtractKeywordResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::voice_keyword_extractor::ExtractKeywordResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "keyword: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.keyword);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "transcript: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.transcript);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "raw_result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.raw_result);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "error_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.error_message);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "processing_time: ";
    Printer<float>::stream(s, indent + "  ", v.processing_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOICE_KEYWORD_EXTRACTOR_MESSAGE_EXTRACTKEYWORDRESPONSE_H
