// Generated by gencpp from file cloud_tts/SynthesizeSpeechRequest.msg
// DO NOT EDIT!


#ifndef CLOUD_TTS_MESSAGE_SYNTHESIZESPEECHREQUEST_H
#define CLOUD_TTS_MESSAGE_SYNTHESIZESPEECHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cloud_tts
{
template <class ContainerAllocator>
struct SynthesizeSpeechRequest_
{
  typedef SynthesizeSpeechRequest_<ContainerAllocator> Type;

  SynthesizeSpeechRequest_()
    : text()
    , play_audio(false)  {
    }
  SynthesizeSpeechRequest_(const ContainerAllocator& _alloc)
    : text(_alloc)
    , play_audio(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _text_type;
  _text_type text;

   typedef uint8_t _play_audio_type;
  _play_audio_type play_audio;





  typedef boost::shared_ptr< ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SynthesizeSpeechRequest_

typedef ::cloud_tts::SynthesizeSpeechRequest_<std::allocator<void> > SynthesizeSpeechRequest;

typedef boost::shared_ptr< ::cloud_tts::SynthesizeSpeechRequest > SynthesizeSpeechRequestPtr;
typedef boost::shared_ptr< ::cloud_tts::SynthesizeSpeechRequest const> SynthesizeSpeechRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator1> & lhs, const ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator2> & rhs)
{
  return lhs.text == rhs.text &&
    lhs.play_audio == rhs.play_audio;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator1> & lhs, const ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cloud_tts

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "998a49c3d49b92ef3b081db6f4fd756c";
  }

  static const char* value(const ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x998a49c3d49b92efULL;
  static const uint64_t static_value2 = 0x3b081db6f4fd756cULL;
};

template<class ContainerAllocator>
struct DataType< ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cloud_tts/SynthesizeSpeechRequest";
  }

  static const char* value(const ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text\n"
"bool play_audio\n"
;
  }

  static const char* value(const ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
      stream.next(m.play_audio);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SynthesizeSpeechRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cloud_tts::SynthesizeSpeechRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.text);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "play_audio: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.play_audio);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLOUD_TTS_MESSAGE_SYNTHESIZESPEECHREQUEST_H
