// Generated by gencpp from file cloud_tts/SynthesizeSpeech.msg
// DO NOT EDIT!


#ifndef CLOUD_TTS_MESSAGE_SYNTHESIZESPEECH_H
#define CLOUD_TTS_MESSAGE_SYNTHESIZESPEECH_H

#include <ros/service_traits.h>


#include <cloud_tts/SynthesizeSpeechRequest.h>
#include <cloud_tts/SynthesizeSpeechResponse.h>


namespace cloud_tts
{

struct SynthesizeSpeech
{

typedef SynthesizeSpeechRequest Request;
typedef SynthesizeSpeechResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SynthesizeSpeech
} // namespace cloud_tts


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cloud_tts::SynthesizeSpeech > {
  static const char* value()
  {
    return "34da7af1fde48d1628d738c7d04b1734";
  }

  static const char* value(const ::cloud_tts::SynthesizeSpeech&) { return value(); }
};

template<>
struct DataType< ::cloud_tts::SynthesizeSpeech > {
  static const char* value()
  {
    return "cloud_tts/SynthesizeSpeech";
  }

  static const char* value(const ::cloud_tts::SynthesizeSpeech&) { return value(); }
};


// service_traits::MD5Sum< ::cloud_tts::SynthesizeSpeechRequest> should match
// service_traits::MD5Sum< ::cloud_tts::SynthesizeSpeech >
template<>
struct MD5Sum< ::cloud_tts::SynthesizeSpeechRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cloud_tts::SynthesizeSpeech >::value();
  }
  static const char* value(const ::cloud_tts::SynthesizeSpeechRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cloud_tts::SynthesizeSpeechRequest> should match
// service_traits::DataType< ::cloud_tts::SynthesizeSpeech >
template<>
struct DataType< ::cloud_tts::SynthesizeSpeechRequest>
{
  static const char* value()
  {
    return DataType< ::cloud_tts::SynthesizeSpeech >::value();
  }
  static const char* value(const ::cloud_tts::SynthesizeSpeechRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cloud_tts::SynthesizeSpeechResponse> should match
// service_traits::MD5Sum< ::cloud_tts::SynthesizeSpeech >
template<>
struct MD5Sum< ::cloud_tts::SynthesizeSpeechResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cloud_tts::SynthesizeSpeech >::value();
  }
  static const char* value(const ::cloud_tts::SynthesizeSpeechResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cloud_tts::SynthesizeSpeechResponse> should match
// service_traits::DataType< ::cloud_tts::SynthesizeSpeech >
template<>
struct DataType< ::cloud_tts::SynthesizeSpeechResponse>
{
  static const char* value()
  {
    return DataType< ::cloud_tts::SynthesizeSpeech >::value();
  }
  static const char* value(const ::cloud_tts::SynthesizeSpeechResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLOUD_TTS_MESSAGE_SYNTHESIZESPEECH_H
