// Generated by gencpp from file cloud_tts/SynthesizeSpeechResponse.msg
// DO NOT EDIT!


#ifndef CLOUD_TTS_MESSAGE_SYNTHESIZESPEECHRESPONSE_H
#define CLOUD_TTS_MESSAGE_SYNTHESIZESPEECHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cloud_tts
{
template <class ContainerAllocator>
struct SynthesizeSpeechResponse_
{
  typedef SynthesizeSpeechResponse_<ContainerAllocator> Type;

  SynthesizeSpeechResponse_()
    : success(false)
    , audio_path()
    , error_message()
    , processing_time(0.0)  {
    }
  SynthesizeSpeechResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , audio_path(_alloc)
    , error_message(_alloc)
    , processing_time(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _audio_path_type;
  _audio_path_type audio_path;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _error_message_type;
  _error_message_type error_message;

   typedef float _processing_time_type;
  _processing_time_type processing_time;





  typedef boost::shared_ptr< ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SynthesizeSpeechResponse_

typedef ::cloud_tts::SynthesizeSpeechResponse_<std::allocator<void> > SynthesizeSpeechResponse;

typedef boost::shared_ptr< ::cloud_tts::SynthesizeSpeechResponse > SynthesizeSpeechResponsePtr;
typedef boost::shared_ptr< ::cloud_tts::SynthesizeSpeechResponse const> SynthesizeSpeechResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator1> & lhs, const ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.audio_path == rhs.audio_path &&
    lhs.error_message == rhs.error_message &&
    lhs.processing_time == rhs.processing_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator1> & lhs, const ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cloud_tts

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "28b8abf06e26fa89b8f143ddc0a9c3db";
  }

  static const char* value(const ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x28b8abf06e26fa89ULL;
  static const uint64_t static_value2 = 0xb8f143ddc0a9c3dbULL;
};

template<class ContainerAllocator>
struct DataType< ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cloud_tts/SynthesizeSpeechResponse";
  }

  static const char* value(const ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string audio_path\n"
"string error_message\n"
"float32 processing_time\n"
"\n"
;
  }

  static const char* value(const ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.audio_path);
      stream.next(m.error_message);
      stream.next(m.processing_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SynthesizeSpeechResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cloud_tts::SynthesizeSpeechResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "audio_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.audio_path);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "error_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.error_message);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "processing_time: ";
    Printer<float>::stream(s, indent + "  ", v.processing_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLOUD_TTS_MESSAGE_SYNTHESIZESPEECHRESPONSE_H
